package com.releasecanvas.app.data.pdf

import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.text.Layout
import android.text.StaticLayout
import android.text.TextPaint
import com.releasecanvas.app.data.model.LocationStatus
import com.releasecanvas.app.data.model.PhotographerProfile
import com.releasecanvas.app.data.model.ReleaseDraft
import com.releasecanvas.app.data.model.SigningMetadata
import com.releasecanvas.app.util.Formatters
import java.io.ByteArrayOutputStream
import java.io.File

/**
 * Builds a US Letter PDF. Content that exceeds the bottom margin flows onto
 * additional pages automatically.
 */
class PdfCompiler {

    fun compile(
        draft: ReleaseDraft,
        metadata: SigningMetadata,
        attestationAccepted: Boolean = false,
        profile: PhotographerProfile = PhotographerProfile(),
    ): ByteArray {
        val document = PdfDocument()
        val accent = parseAccent(profile.brandAccentHex)
        val writer = PaginatedWriter(document, accentColor = accent)

        val template = draft.template
        if (profile.brandingEnabled) {
            writer.drawBrandingHeader(profile)
        }
        writer.drawTitle("Model Release Agreement")
        writer.drawMetaLine(
            "Generated by ReleaseCanvas · ${template.displayName} · ${template.version}",
        )
        writer.gap()
        writer.drawHeading("Parties")
        writer.drawBody("Model: ${draft.modelName}")
        writer.drawBody("Model email: ${draft.modelEmail}")
        writer.drawBody("Photographer: ${draft.shooterName}")
        if (profile.brandingEnabled) {
            optionalLine(profile.studioName)?.let { writer.drawBody("Studio: $it") }
        }
        optionalLine(draft.photographerEmail)?.let { writer.drawBody("Photographer email: $it") }
        optionalLine(draft.photographerPhone)?.let { writer.drawBody("Photographer phone: $it") }
        optionalLine(draft.clientAgency)?.let { writer.drawBody("Client / agency: $it") }
        writer.gap()
        writer.drawHeading("Shoot details")
        optionalLine(draft.shootId)?.let { writer.drawBody("Shoot ID: $it") }
        optionalLine(draft.locationName)?.let { writer.drawBody("Shoot location: $it") }
        writer.drawBody("Description: ${draft.description.trim()}")
        optionalLine(draft.notes)?.let { writer.drawWrapped("Notes: $it", writer.bodyPaint) }
        writer.gap()
        writer.drawHeading("Release terms")
        writer.drawBody("Template: ${template.displayName}")
        val terms = ReleaseTerms.body(template, draft.modelName.trim(), draft.shooterName.trim())
        writer.drawWrapped(terms, writer.smallPaint)
        writer.gap()
        writer.drawHeading("Signature")
        writer.drawSignature(draft.signatureBitmap)
        writer.gap()
        writer.drawHeading("Signing metadata")
        writer.drawBody("Signed at (UTC): ${Formatters.formatUtc(metadata.signedAtUtc)}")
        Formatters.formatPlaceLabel(metadata)?.let { place ->
            val source = Formatters.formatPlaceSource(metadata.placeSource)?.let { " ($it)" }.orEmpty()
            writer.drawBody("Place: $place$source")
        }
        val coords = Formatters.formatCoordinates(metadata)
        writer.drawBody("GPS: ${coords ?: unavailableGpsReason(metadata.locationStatus)}")
        writer.drawBody("Location status: ${statusLabel(metadata.locationStatus)}")
        if (attestationAccepted) {
            writer.drawWrapped(
                "Attestation: Model confirmed they are of legal age of majority " +
                    "(or parent/guardian with authority) and accept the terms above.",
                writer.bodyPaint,
            )
        }
        writer.gap()
        writer.drawWrapped(
            "This electronic signature and metadata stamp are intended for record-keeping. " +
                "Not a substitute for legal advice.",
            writer.smallPaint,
        )
        if (profile.brandingEnabled) {
            writer.gap()
            val studio = profile.studioName.trim().ifBlank { profile.displayName.trim() }
            if (studio.isNotEmpty()) {
                writer.drawMetaLine("Prepared by $studio · ReleaseCanvas")
            }
        }

        writer.finish()
        val out = ByteArrayOutputStream()
        document.writeTo(out)
        document.close()
        return out.toByteArray()
    }

    private fun parseAccent(hex: String): Int = runCatching {
        Color.parseColor(hex.trim().ifBlank { "#3A86FF" })
    }.getOrDefault(Color.parseColor("#3A86FF"))

    private fun optionalLine(value: String): String? =
        value.trim().takeIf { it.isNotEmpty() }

    private fun statusLabel(status: LocationStatus): String = when (status) {
        LocationStatus.Available -> "Available"
        LocationStatus.PermissionDenied -> "Permission denied"
        LocationStatus.Unavailable -> "Unavailable"
        LocationStatus.Timeout -> "Timeout"
        LocationStatus.Acquiring -> "Acquiring"
    }

    private fun unavailableGpsReason(status: LocationStatus): String = when (status) {
        LocationStatus.PermissionDenied -> "unavailable (permission denied)"
        LocationStatus.Timeout -> "unavailable (timeout)"
        LocationStatus.Unavailable -> "unavailable"
        LocationStatus.Acquiring -> "acquiring"
        LocationStatus.Available -> "unavailable"
    }

    private class PaginatedWriter(
        private val document: PdfDocument,
        private val accentColor: Int = Color.BLACK,
    ) {
        private var pageNumber = 0
        private var page: PdfDocument.Page? = null
        private var canvas: Canvas? = null
        private var y = MARGIN.toFloat()

        val titlePaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.BLACK
            textSize = 20f
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.BOLD)
        }
        val headingPaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
            color = accentColor
            textSize = 13f
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.BOLD)
        }
        val bodyPaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.BLACK
            textSize = 11f
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.NORMAL)
        }
        val smallPaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
            color = Color.DKGRAY
            textSize = 9.5f
            typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.NORMAL)
        }

        init {
            startPage()
        }

        fun gap() {
            ensureSpace(SECTION_GAP + 4f)
            y += SECTION_GAP
        }

        fun drawTitle(text: String) {
            ensureSpace(titlePaint.textSize + 12f)
            canvas!!.drawText(text, MARGIN.toFloat(), y + titlePaint.textSize, titlePaint)
            y += titlePaint.textSize + 8f
        }

        fun drawMetaLine(text: String) {
            ensureSpace(smallPaint.textSize + 8f)
            canvas!!.drawText(text, MARGIN.toFloat(), y + smallPaint.textSize, smallPaint)
            y += smallPaint.textSize + 4f
        }

        fun drawBrandingHeader(profile: PhotographerProfile) {
            val logoFile = profile.logoPath.takeIf { it.isNotBlank() }?.let { File(it) }
            val logo = if (logoFile != null && logoFile.exists()) {
                BitmapFactory.decodeFile(logoFile.absolutePath)
            } else {
                null
            }
            if (logo != null && !logo.isRecycled) {
                val maxH = 48f
                val maxW = 120f
                val scale = minOf(maxW / logo.width, maxH / logo.height, 1f)
                val w = logo.width * scale
                val h = logo.height * scale
                ensureSpace(h + 16f)
                canvas!!.drawBitmap(
                    logo,
                    null,
                    android.graphics.RectF(MARGIN.toFloat(), y, MARGIN + w, y + h),
                    Paint(Paint.FILTER_BITMAP_FLAG),
                )
                y += h + 6f
            }
            val studio = profile.studioName.trim().ifBlank { profile.displayName.trim() }
            if (studio.isNotEmpty()) {
                ensureSpace(headingPaint.textSize + 10f)
                canvas!!.drawText(studio, MARGIN.toFloat(), y + headingPaint.textSize, headingPaint)
                y += headingPaint.textSize + 4f
            }
            // Accent rule
            ensureSpace(8f)
            val line = Paint(Paint.ANTI_ALIAS_FLAG).apply {
                color = accentColor
                strokeWidth = 2f
            }
            canvas!!.drawLine(
                MARGIN.toFloat(),
                y,
                (PAGE_WIDTH - MARGIN).toFloat(),
                y,
                line,
            )
            y += 10f
        }

        fun drawHeading(text: String) {
            ensureSpace(headingPaint.textSize + 10f)
            canvas!!.drawText(text, MARGIN.toFloat(), y + headingPaint.textSize, headingPaint)
            y += headingPaint.textSize + 6f
        }

        fun drawBody(text: String) = drawWrapped(text, bodyPaint)

        fun drawWrapped(text: String, paint: TextPaint) {
            val layout = StaticLayout.Builder.obtain(text, 0, text.length, paint, CONTENT_WIDTH)
                .setAlignment(Layout.Alignment.ALIGN_NORMAL)
                .setLineSpacing(0f, 1.15f)
                .setIncludePad(false)
                .build()
            // If block is taller than a full page content area, draw line-by-line
            val maxBlock = PAGE_HEIGHT - MARGIN * 2
            if (layout.height > maxBlock) {
                drawLayoutPaginated(layout)
                return
            }
            ensureSpace(layout.height + 4f)
            canvas!!.save()
            canvas!!.translate(MARGIN.toFloat(), y)
            layout.draw(canvas!!)
            canvas!!.restore()
            y += layout.height + 4f
        }

        private fun drawLayoutPaginated(layout: StaticLayout) {
            var line = 0
            while (line < layout.lineCount) {
                val lineBottom = layout.getLineBottom(line) - layout.getLineTop(line)
                ensureSpace(lineBottom + 2f)
                val top = layout.getLineTop(line)
                canvas!!.save()
                canvas!!.translate(MARGIN.toFloat(), y - top)
                // clip to single line band
                canvas!!.clipRect(0, top, CONTENT_WIDTH, layout.getLineBottom(line))
                layout.draw(canvas!!)
                canvas!!.restore()
                y += lineBottom + 2f
                line++
            }
            y += 2f
        }

        fun drawSignature(signature: Bitmap?) {
            if (signature == null || signature.isRecycled) {
                drawBody("[No signature image]")
                return
            }
            val maxWidth = 220f
            val maxHeight = 90f
            val scale = minOf(maxWidth / signature.width, maxHeight / signature.height, 1f)
            val width = signature.width * scale
            val height = signature.height * scale
            ensureSpace(height + 10f)
            val destLeft = MARGIN.toFloat()
            val destTop = y
            val borderPaint = Paint().apply {
                color = Color.LTGRAY
                style = Paint.Style.STROKE
                strokeWidth = 1f
            }
            canvas!!.drawRect(destLeft, destTop, destLeft + width, destTop + height, borderPaint)
            canvas!!.drawBitmap(
                signature,
                null,
                android.graphics.RectF(destLeft, destTop, destLeft + width, destTop + height),
                Paint(Paint.FILTER_BITMAP_FLAG),
            )
            y = destTop + height + 6f
        }

        fun finish() {
            page?.let { document.finishPage(it) }
            page = null
            canvas = null
        }

        private fun ensureSpace(needed: Float) {
            val bottom = PAGE_HEIGHT - MARGIN
            if (y + needed > bottom) {
                startPage()
            }
        }

        private fun startPage() {
            page?.let { document.finishPage(it) }
            pageNumber += 1
            val info = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
            page = document.startPage(info)
            canvas = page!!.canvas
            y = MARGIN.toFloat()
            if (pageNumber > 1) {
                canvas!!.drawText(
                    "ReleaseCanvas · continued (page $pageNumber)",
                    MARGIN.toFloat(),
                    y + smallPaint.textSize,
                    smallPaint,
                )
                y += smallPaint.textSize + 10f
            }
        }
    }

    companion object {
        const val PAGE_WIDTH = 612
        const val PAGE_HEIGHT = 792
        const val MARGIN = 48
        val CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2
        const val SECTION_GAP = 10f
    }
}
