package com.releasecanvas.app.data.pdf

import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.text.Layout
import android.text.StaticLayout
import android.text.TextPaint
import com.releasecanvas.app.data.model.LocationStatus
import com.releasecanvas.app.data.model.ReleaseDraft
import com.releasecanvas.app.data.model.SigningMetadata
import com.releasecanvas.app.util.Formatters
import java.io.ByteArrayOutputStream

class PdfCompiler {

    fun compile(draft: ReleaseDraft, metadata: SigningMetadata): ByteArray {
        val document = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, 1).create()
        val page = document.startPage(pageInfo)
        val canvas = page.canvas

        var y = MARGIN.toFloat()
        y = drawTitle(canvas, y)
        y = drawMetaLine(canvas, y, "Generated by ReleaseCanvas · Terms ${ReleaseTerms.VERSION}")
        y += SECTION_GAP
        y = drawSectionHeading(canvas, y, "Parties")
        y = drawBodyLine(canvas, y, "Model: ${draft.modelName}")
        y = drawBodyLine(canvas, y, "Model email: ${draft.modelEmail}")
        y = drawBodyLine(canvas, y, "Photographer: ${draft.shooterName}")
        optionalLine(draft.photographerEmail)?.let { y = drawBodyLine(canvas, y, "Photographer email: $it") }
        optionalLine(draft.photographerPhone)?.let { y = drawBodyLine(canvas, y, "Photographer phone: $it") }
        optionalLine(draft.clientAgency)?.let { y = drawBodyLine(canvas, y, "Client / agency: $it") }
        y += SECTION_GAP
        y = drawSectionHeading(canvas, y, "Shoot details")
        optionalLine(draft.shootId)?.let { y = drawBodyLine(canvas, y, "Shoot ID: $it") }
        optionalLine(draft.locationName)?.let { y = drawBodyLine(canvas, y, "Shoot location: $it") }
        y = drawBodyLine(canvas, y, "Description: ${draft.description.trim()}")
        optionalLine(draft.notes)?.let {
            y = drawWrapped(canvas, y, "Notes: $it", bodyPaint)
        }
        y += SECTION_GAP
        y = drawSectionHeading(canvas, y, "Release terms")
        val terms = ReleaseTerms.body(draft.modelName.trim(), draft.shooterName.trim())
        y = drawWrapped(canvas, y, terms, smallPaint)
        y += SECTION_GAP
        y = drawSectionHeading(canvas, y, "Signature")
        y = drawSignature(canvas, y, draft.signatureBitmap)
        y += SECTION_GAP
        y = drawSectionHeading(canvas, y, "Signing metadata")
        y = drawBodyLine(canvas, y, "Signed at (UTC): ${Formatters.formatUtc(metadata.signedAtUtc)}")
        Formatters.formatPlaceLabel(metadata)?.let { place ->
            val source = Formatters.formatPlaceSource(metadata.placeSource)?.let { " ($it)" }.orEmpty()
            y = drawBodyLine(canvas, y, "Place: $place$source")
        }
        val coords = Formatters.formatCoordinates(metadata)
        y = drawBodyLine(
            canvas,
            y,
            "GPS: ${coords ?: unavailableGpsReason(metadata.locationStatus)}",
        )
        y = drawBodyLine(canvas, y, "Location status: ${statusLabel(metadata.locationStatus)}")
        y += SECTION_GAP
        drawFooter(canvas, y)

        document.finishPage(page)
        val out = ByteArrayOutputStream()
        document.writeTo(out)
        document.close()
        return out.toByteArray()
    }

    private fun drawTitle(canvas: Canvas, y: Float): Float {
        canvas.drawText("Model Release Agreement", MARGIN.toFloat(), y + titlePaint.textSize, titlePaint)
        return y + titlePaint.textSize + 8f
    }

    private fun drawMetaLine(canvas: Canvas, y: Float, text: String): Float {
        canvas.drawText(text, MARGIN.toFloat(), y + smallPaint.textSize, smallPaint)
        return y + smallPaint.textSize + 4f
    }

    private fun drawSectionHeading(canvas: Canvas, y: Float, text: String): Float {
        canvas.drawText(text, MARGIN.toFloat(), y + headingPaint.textSize, headingPaint)
        return y + headingPaint.textSize + 6f
    }

    private fun drawBodyLine(canvas: Canvas, y: Float, text: String): Float {
        return drawWrapped(canvas, y, text, bodyPaint)
    }

    private fun drawWrapped(canvas: Canvas, y: Float, text: String, paint: TextPaint): Float {
        val layout = StaticLayout.Builder.obtain(text, 0, text.length, paint, CONTENT_WIDTH)
            .setAlignment(Layout.Alignment.ALIGN_NORMAL)
            .setLineSpacing(0f, 1.15f)
            .setIncludePad(false)
            .build()
        canvas.save()
        canvas.translate(MARGIN.toFloat(), y)
        layout.draw(canvas)
        canvas.restore()
        return y + layout.height + 4f
    }

    private fun drawSignature(canvas: Canvas, y: Float, signature: Bitmap?): Float {
        if (signature == null || signature.isRecycled) {
            return drawBodyLine(canvas, y, "[No signature image]")
        }
        val maxWidth = 220f
        val maxHeight = 90f
        val scale = minOf(maxWidth / signature.width, maxHeight / signature.height, 1f)
        val width = signature.width * scale
        val height = signature.height * scale
        val destLeft = MARGIN.toFloat()
        val destTop = y
        val borderPaint = Paint().apply {
            color = Color.LTGRAY
            style = Paint.Style.STROKE
            strokeWidth = 1f
        }
        canvas.drawRect(destLeft, destTop, destLeft + width, destTop + height, borderPaint)
        canvas.drawBitmap(
            signature,
            null,
            android.graphics.RectF(destLeft, destTop, destLeft + width, destTop + height),
            Paint(Paint.FILTER_BITMAP_FLAG),
        )
        return destTop + height + 6f
    }

    private fun drawFooter(canvas: Canvas, y: Float) {
        val footer = "This electronic signature and metadata stamp are intended for record-keeping. " +
            "Not a substitute for legal advice."
        drawWrapped(canvas, y, footer, smallPaint)
    }

    private fun optionalLine(value: String): String? =
        value.trim().takeIf { it.isNotEmpty() }

    private fun statusLabel(status: LocationStatus): String = when (status) {
        LocationStatus.Available -> "Available"
        LocationStatus.PermissionDenied -> "Permission denied"
        LocationStatus.Unavailable -> "Unavailable"
        LocationStatus.Timeout -> "Timeout"
        LocationStatus.Acquiring -> "Acquiring"
    }

    private fun unavailableGpsReason(status: LocationStatus): String = when (status) {
        LocationStatus.PermissionDenied -> "unavailable (permission denied)"
        LocationStatus.Timeout -> "unavailable (timeout)"
        LocationStatus.Unavailable -> "unavailable"
        LocationStatus.Acquiring -> "acquiring"
        LocationStatus.Available -> "unavailable"
    }

    private val titlePaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
        color = Color.BLACK
        textSize = 20f
        typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.BOLD)
    }

    private val headingPaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
        color = Color.BLACK
        textSize = 13f
        typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.BOLD)
    }

    private val bodyPaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
        color = Color.BLACK
        textSize = 11f
        typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.NORMAL)
    }

    private val smallPaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
        color = Color.DKGRAY
        textSize = 9.5f
        typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.NORMAL)
    }

    companion object {
        // US Letter in points (1/72")
        const val PAGE_WIDTH = 612
        const val PAGE_HEIGHT = 792
        const val MARGIN = 48
        val CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2
        const val SECTION_GAP = 10f
    }
}
