package com.releasecanvas.app.data.pdf

import com.releasecanvas.app.data.locale.AppLocale

/** PDF chrome labels in the release/template language (not UI language). */
data class PdfLabels(
    val title: String,
    val generated: String,
    val parties: String,
    val model: String,
    val model_email: String,
    val photographer: String,
    val studio: String,
    val photographer_email: String,
    val photographer_phone: String,
    val client: String,
    val shoot: String,
    val shoot_id: String,
    val shoot_location: String,
    val description: String,
    val notes: String,
    val terms: String,
    val template: String,
    val signature: String,
    val no_sig: String,
    val metadata: String,
    val signed_utc: String,
    val place: String,
    val gps: String,
    val location_status: String,
    val attestation: String,
    val footer: String,
    val prepared: String,
    val continued: String,
    val status_available: String,
    val status_denied: String,
    val status_unavailable: String,
    val status_timeout: String,
    val status_acquiring: String,
    val gps_denied: String,
    val gps_timeout: String,
    val gps_unavailable: String,
    val gps_acquiring: String,
)

object PdfLabelCatalog {

    fun forLanguage(languageTag: String): PdfLabels {
        val lang = AppLocale.normalizeReleaseTag(languageTag)
        return labels[lang] ?: labels.getValue("en")
    }

    private val labels: Map<String, PdfLabels> = mapOf(
        "en" to PdfLabels(title = "Model Release Agreement", generated = "Generated by ReleaseCanvas", parties = "Parties", model = "Model", model_email = "Model email", photographer = "Photographer", studio = "Studio", photographer_email = "Photographer email", photographer_phone = "Photographer phone", client = "Client / agency", shoot = "Shoot details", shoot_id = "Shoot ID", shoot_location = "Shoot location", description = "Description", notes = "Notes", terms = "Release terms", template = "Template", signature = "Signature", no_sig = "[No signature image]", metadata = "Signing metadata", signed_utc = "Signed at (UTC)", place = "Place", gps = "GPS", location_status = "Location status", attestation = "Attestation: Model confirmed they are of legal age of majority (or parent/guardian with authority) and accept the terms above.", footer = "This electronic signature and metadata stamp are intended for record-keeping. Not a substitute for legal advice.", prepared = "Prepared by %s · ReleaseCanvas", continued = "ReleaseCanvas · continued (page %d)", status_available = "Available", status_denied = "Permission denied", status_unavailable = "Unavailable", status_timeout = "Timeout", status_acquiring = "Acquiring", gps_denied = "unavailable (permission denied)", gps_timeout = "unavailable (timeout)", gps_unavailable = "unavailable", gps_acquiring = "acquiring"),
        "es" to PdfLabels(title = "Acuerdo de cesión de imagen", generated = "Generado por ReleaseCanvas", parties = "Partes", model = "Modelo", model_email = "Email del modelo", photographer = "Fotógrafo", studio = "Estudio", photographer_email = "Email del fotógrafo", photographer_phone = "Teléfono del fotógrafo", client = "Cliente / agencia", shoot = "Detalles de la sesión", shoot_id = "ID de sesión", shoot_location = "Ubicación de la sesión", description = "Descripción", notes = "Notas", terms = "Términos de cesión", template = "Plantilla", signature = "Firma", no_sig = "[Sin imagen de firma]", metadata = "Metadatos de firma", signed_utc = "Firmado (UTC)", place = "Lugar", gps = "GPS", location_status = "Estado de ubicación", attestation = "Atestación: el Modelo confirma ser mayor de edad (o padre/tutor con autoridad) y acepta los términos anteriores.", footer = "Esta firma electrónica y metadatos son para registro. No sustituyen asesoramiento legal.", prepared = "Preparado por %s · ReleaseCanvas", continued = "ReleaseCanvas · continúa (página %d)", status_available = "Disponible", status_denied = "Permiso denegado", status_unavailable = "No disponible", status_timeout = "Tiempo agotado", status_acquiring = "Obteniendo", gps_denied = "no disponible (permiso denegado)", gps_timeout = "no disponible (tiempo agotado)", gps_unavailable = "no disponible", gps_acquiring = "obteniendo"),
        "fr" to PdfLabels(title = "Autorisation de droit à l’image", generated = "Généré par ReleaseCanvas", parties = "Parties", model = "Modèle", model_email = "E-mail du modèle", photographer = "Photographe", studio = "Studio", photographer_email = "E-mail du photographe", photographer_phone = "Téléphone du photographe", client = "Client / agence", shoot = "Détails de la séance", shoot_id = "ID de séance", shoot_location = "Lieu de la séance", description = "Description", notes = "Notes", terms = "Conditions de l’autorisation", template = "Modèle", signature = "Signature", no_sig = "[Pas d’image de signature]", metadata = "Métadonnées de signature", signed_utc = "Signé le (UTC)", place = "Lieu", gps = "GPS", location_status = "État de localisation", attestation = "Attestation : le Modèle confirme être majeur (ou parent/tuteur habilité) et accepte les conditions ci-dessus.", footer = "Cette signature électronique et ces métadonnées sont destinées à l’archivage. Ne remplacent pas un conseil juridique.", prepared = "Préparé par %s · ReleaseCanvas", continued = "ReleaseCanvas · suite (page %d)", status_available = "Disponible", status_denied = "Permission refusée", status_unavailable = "Indisponible", status_timeout = "Délai dépassé", status_acquiring = "Acquisition", gps_denied = "indisponible (permission refusée)", gps_timeout = "indisponible (délai)", gps_unavailable = "indisponible", gps_acquiring = "acquisition"),
        "it" to PdfLabels(title = "Liberatoria per l’immagine", generated = "Generato da ReleaseCanvas", parties = "Parti", model = "Modello", model_email = "Email del modello", photographer = "Fotografo", studio = "Studio", photographer_email = "Email del fotografo", photographer_phone = "Telefono del fotografo", client = "Cliente / agenzia", shoot = "Dettagli della sessione", shoot_id = "ID sessione", shoot_location = "Luogo della sessione", description = "Descrizione", notes = "Note", terms = "Termini della liberatoria", template = "Modello", signature = "Firma", no_sig = "[Nessuna immagine di firma]", metadata = "Metadati di firma", signed_utc = "Firmato il (UTC)", place = "Luogo", gps = "GPS", location_status = "Stato posizione", attestation = "Attestazione: il Modello conferma di essere maggiorenne (o genitore/tutore con autorità) e di accettare i termini di cui sopra.", footer = "Questa firma elettronica e i metadati sono a scopo di registrazione. Non sostituiscono consulenza legale.", prepared = "Preparato da %s · ReleaseCanvas", continued = "ReleaseCanvas · continua (pagina %d)", status_available = "Disponibile", status_denied = "Permesso negato", status_unavailable = "Non disponibile", status_timeout = "Timeout", status_acquiring = "Acquisizione", gps_denied = "non disponibile (permesso negato)", gps_timeout = "non disponibile (timeout)", gps_unavailable = "non disponibile", gps_acquiring = "acquisizione"),
        "de" to PdfLabels(title = "Model-Release-Vereinbarung", generated = "Erstellt mit ReleaseCanvas", parties = "Parteien", model = "Model", model_email = "E-Mail des Models", photographer = "Fotograf", studio = "Studio", photographer_email = "E-Mail des Fotografen", photographer_phone = "Telefon des Fotografen", client = "Kunde / Agentur", shoot = "Shooting-Details", shoot_id = "Shooting-ID", shoot_location = "Shooting-Ort", description = "Beschreibung", notes = "Notizen", terms = "Freigabebedingungen", template = "Vorlage", signature = "Unterschrift", no_sig = "[Kein Unterschriftsbild]", metadata = "Signatur-Metadaten", signed_utc = "Unterzeichnet (UTC)", place = "Ort", gps = "GPS", location_status = "Standortstatus", attestation = "Bestätigung: Das Model bestätigt die Volljährigkeit (oder Erziehungsberechtigung) und akzeptiert die obigen Bedingungen.", footer = "Diese elektronische Unterschrift und Metadaten dienen der Dokumentation. Kein Ersatz für Rechtsberatung.", prepared = "Erstellt von %s · ReleaseCanvas", continued = "ReleaseCanvas · Fortsetzung (Seite %d)", status_available = "Verfügbar", status_denied = "Berechtigung verweigert", status_unavailable = "Nicht verfügbar", status_timeout = "Zeitüberschreitung", status_acquiring = "Wird ermittelt", gps_denied = "nicht verfügbar (Berechtigung verweigert)", gps_timeout = "nicht verfügbar (Zeitüberschreitung)", gps_unavailable = "nicht verfügbar", gps_acquiring = "wird ermittelt"),
        "fa" to PdfLabels(title = "رضایت‌نامه مدل", generated = "تولیدشده با ReleaseCanvas", parties = "طرفین", model = "مدل", model_email = "ایمیل مدل", photographer = "عکاس", studio = "استودیو", photographer_email = "ایمیل عکاس", photographer_phone = "تلفن عکاس", client = "کارفرما / آژانس", shoot = "جزئیات جلسه", shoot_id = "شناسه جلسه", shoot_location = "مکان جلسه", description = "توضیحات", notes = "یادداشت‌ها", terms = "شرایط رضایت‌نامه", template = "قالب", signature = "امضا", no_sig = "[بدون تصویر امضا]", metadata = "فراداده امضا", signed_utc = "زمان امضا (UTC)", place = "مکان", gps = "جی‌پی‌اس", location_status = "وضعیت موقعیت", attestation = "تأیید: مدل اعلام می‌کند به سن قانونی رسیده (یا ولی/سرپرست با اختیار است) و شرایط بالا را می‌پذیرد.", footer = "این امضای الکترونیکی و فراداده برای بایگانی است و جایگزین مشاوره حقوقی نیست.", prepared = "تهیه‌شده توسط %s · ReleaseCanvas", continued = "ReleaseCanvas · ادامه (صفحه %d)", status_available = "موجود", status_denied = "مجوز رد شد", status_unavailable = "در دسترس نیست", status_timeout = "اتمام زمان", status_acquiring = "در حال دریافت", gps_denied = "در دسترس نیست (مجوز رد شد)", gps_timeout = "در دسترس نیست (اتمام زمان)", gps_unavailable = "در دسترس نیست", gps_acquiring = "در حال دریافت"),
    )
}
